// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbzwchnxtskysqplqiyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iendjaG54dHNreXNxcGxxaXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDg3OTUsImV4cCI6MjA3MzcyNDc5NX0.HOc6OPJWLFx7CosscbTiRlscbX44BEySMtFAI49_G2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});